env:
  "browser": true
  "node": true
  "es6": true
  "jest": true

extends:
  - 'eslint:recommended'
  - 'plugin:vue/recommended'

rules:
  "vue/no-unused-vars": "error"
  "vue/html-indent": ["error", 4, {"baseIndent": 1}]
  "vue/html-closing-bracket-spacing": ["error", {
    "startTag": "never",
    "endTag": "never",
    "selfClosingTag": "never"
  }]
